### ISSUE TITLE
Semantic Versioning

### ISSUE THREAD

**Issue by kecorbin** [mocofound/terraform-aws-consumer-ec2-instance#2]
Hey @mocofound I had some issues using a fork of this.  It appears there is now a strict enforcement of semantic versioning.  I had to add tags like 1.7.0 etc to my fork.  Maybe I'm doing something wrong, or maybe we should add tags here.  You appear to be the source.

**Comment by mocofound** [comment]
Thanks, will switch to semantec Versioning for next release.

**Comment by mocofound** [comment]
Release 1.24.0 is SemVer.  Closing.  Thanks!
